### ISSUE TITLE
Documentar e comparar diferentes estratégias de ETL para dados CNPJ

### ISSUE THREAD

**Issue by caiopizzol** [cnpj-chat/cnpj-data-pipeline#13]
**Descrição:**
O usuário @valterpatrick compartilhou sua estratégia de ETL que difere da nossa abordagem. Precisamos documentar diferentes estratégias possíveis e seus trade-offs para ajudar usuários a escolherem a melhor para seu caso.

**Contexto do comentário:**
> "Eu faço o tratamento dos dados antes de inserir, removendo caracteres, linhas duplicadas e etc. Depois eu importo os dados para uma base de dados vazia através do bulk insert. Logo em seguida eu faço o insert dos dados em outras tabelas já fazendo o tratamento de alguns dados, joins e indices."

TabNews: https://www.tabnews.com.br/valterpatrick/d1c60415-c126-461e-9d9f-083161aa6034

**Estratégias a documentar:**

### 1. Estratégia Atual (Pipeline)
- Processamento incremental
- UPSERT para manter disponibilidade
- Transformações durante o load

### 2. Estratégia @valterpatrick
- Pré-processamento completo
- Carga em DB vazia (bulk insert)
- Pós-processamento com joins/índices

### 3. Estratégia Híbrida
- Limpeza mínima pré-load
- Carga rápida
- Transformações via SQL

**Tarefas:**
- [ ] Criar documento comparando estratégias de ETL
- [ ] Implementar modo "valterpatrick" como opção
- [ ] Benchmark de cada abordagem:
  - [ ] Tempo total de processamento
  - [ ] Uso de memória
  - [ ] Espaço em disco necessário
  - [ ] Complexidade de manutenção
- [ ] Criar fluxogramas para cada estratégia
- [ ] Adicionar configuração para escolher estratégia

**Exemplo de configuração:**
```yaml
etl_strategy: 
  type: "pre_process" | "incremental" | "post_process"
  pre_clean:
    remove_duplicates: true
    fix_encoding: true
    validate_data: true
  load:
    method: "bulk_insert" | "upsert" | "copy"
    target: "empty_db" | "existing_db"
  post_process:
    create_indexes: true
    materialize_views: true
    analyze_tables: true
```

**Documentação esperada:**
```markdown
## Estratégias de ETL

### Quando usar cada uma:

1. **Pre-Process (Estilo @valterpatrick)**
   - ✅ Dados mais limpos
   - ✅ Carga mais rápida
   - ❌ Requer mais espaço temporário
   - 📊 Melhor para: Carga inicial completa

2. **Incremental (Pipeline atual)**
   - ✅ Menor uso de memória
   - ✅ Suporta atualizações
   - ❌ Mais complexo
   - 📊 Melhor para: Atualizações mensais

3. **Post-Process**
   - ✅ Carga ultra-rápida
   - ✅ Transformações em SQL
   - ❌ DB indisponível durante processo
   - 📊 Melhor para: Análise batch
```
---
**English Summary:** Document and compare different ETL strategies based on community feedback. User @valterpatrick shared an approach of pre-cleaning data, bulk loading to empty DB, then post-processing with joins. Need to benchmark and document when to use each strategy (pre-process vs incremental vs post-process).
